server:
  port: 8030
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true